Repository 25MPOOL/HunToru, pull requests merged in 2025-07, with the labels that each got.

#3 プロジェクトのセットアップ
  .cursor/rules/rules.mdc
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  apps/api/.gitignore
  apps/api/README.md
  apps/api/package.json
  apps/api/src/index.ts
  apps/api/tsconfig.json
  apps/api/wrangler.jsonc
  apps/web/.gitignore
  apps/web/README.md
  apps/web/eslint.config.js
  apps/web/index.html
  apps/web/package.json
  apps/web/public/vite.svg
  apps/web/src/App.css
  apps/web/src/App.tsx
  apps/web/src/assets/react.svg
  apps/web/src/index.css
  apps/web/src/main.tsx
  apps/web/src/vite-env.d.ts
  apps/web/tsconfig.app.json
  apps/web/tsconfig.json
  apps/web/tsconfig.node.json
  apps/web/vite.config.ts
  package.json
  packages/.gitkeep
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tsconfig.json
Labels: ⚙️ バックエンド, 🔧 環境, 🖥️ フロントエンド, 📝 ドキュメント

#8 .cursor/rulesに新たなアプリ設計ルールを追加
  .cursor/rules/codingRules.mdc
  .cursor/rules/hunToruDocuments.mdc
  .cursor/rules/huntoruDocuments.mdc
Labels: 🔧 環境, 📝 ドキュメント

#10 .cursor/rulesに一部ミスがあったので修正
  .cursor/rules/hunToruDocuments.mdc
  .cursor/rules/rules.mdc
Labels: 🔧 環境, 📝 ドキュメント

#25 Github Action CI のテストブランチ
  .github/workflows/ci.yml
  .gitignore
  .husky/pre-commit
  .prettierrc
  apps/api/package.json
  apps/web/package.json
  apps/web/src/App.tsx
  apps/web/src/main.tsx
  eslint.config.js
  package.json
  pnpm-lock.yaml
Labels: ⚙️ バックエンド, 🔧 環境, 🖥️ フロントエンド, 🔥 優先度: 高

#28 Feature/12/take photo send photo
  apps/api/src/index.ts
  apps/web/src/App.css
  apps/web/src/App.tsx
  apps/web/src/components/camera/camera.tsx
  apps/web/src/components/camera/index.tsx
  apps/web/src/components/camera/types.ts
  apps/web/src/components/index.tsx
  apps/web/src/index.css
Labels: ✨ 新機能, 🖥️ フロントエンド

#29 Google Cloud Vision APIの実装
  apps/api/.dev.vars.example
  apps/api/package.json
  apps/api/src/index.ts
  apps/api/src/vision-api.ts
  apps/api/wrangler.jsonc
  apps/web/wrangler.jsonc
  pnpm-lock.yaml
Labels: ⚙️ バックエンド, ✨ 新機能

#38 `/themes` エンドポイントで取得するお題の数を1つに修正
  apps/api/src/index.ts
Labels: ⚙️ バックエンド

#40 Feature/16/add game screen
  apps/web/src/App.css
  apps/web/src/App.module.css
  apps/web/src/App.tsx
  apps/web/src/components/camera/camera.module.css
  apps/web/src/components/camera/camera.tsx
  apps/web/src/components/camera/types.ts
  apps/web/src/components/game/shooting-screen.module.css
  apps/web/src/components/game/shooting-screen.tsx
  apps/web/src/components/game/timer.module.css
  apps/web/src/components/game/timer.tsx
  apps/web/src/components/game/types.ts
  apps/web/src/components/index.tsx
  apps/web/src/index.css
Labels: ✨ 新機能, 🎨 UI改善, 🖥️ フロントエンド

#44 結果画面のUI作成
  apps/web/src/App.tsx
  apps/web/src/components/result/ResultScreen.module.css
  apps/web/src/components/result/ResultScreen.tsx
Labels: ✨ 新機能, 🎨 UI改善, 🖥️ フロントエンド

#49 難易度選択画面のUI作成
  apps/web/src/App.tsx
  apps/web/src/components/mode/ModeScreen.module.css
  apps/web/src/components/mode/ModeScreen.tsx
  apps/web/src/components/ui/PixelBubble.tsx
  apps/web/src/index.css
Labels: ✨ 新機能, 🎨 UI改善, 🖥️ フロントエンド

#52 全ページに対して、ルーティング機能を追加
  apps/web/package.json
  apps/web/src/App.tsx
  apps/web/src/components/home/HomeScreen.tsx
  apps/web/src/components/mode/ModeScreen.tsx
  apps/web/src/components/photo/PhotoPreview.tsx
  apps/web/src/components/photo/PhotoScreen.tsx
  apps/web/src/components/result/ResultScreen.tsx
  pnpm-lock.yaml
Labels: ✨ 新機能, 🖥️ フロントエンド

#59 本番環境のWebサーバーURLを修正
  apps/api/wrangler.jsonc
Labels: ⚙️ バックエンド, 🔥 優先度: 高, 🔧 機能修正

#60 Cloudflare D1 にお題をそれぞれ7個ずつ追加
  apps/api/.gitignore
  apps/api/package.json
  apps/api/src/db/seed-data.ts
  apps/api/src/scripts/generate-sql.ts
  apps/api/src/scripts/seed.ts
Labels: ⚙️ バックエンド, 🔥 優先度: 高

#61 本番環境でAPIが叩けない問題を修正した...はず。
  apps/web/package.json
  apps/web/src/components/mode/ModeScreen.tsx
  apps/web/src/components/photo/PhotoPreview.tsx
Labels: 🐛 バグ, 🔥 優先度: 高

#62 baseURLを本番APIサーバーURLに設定
  apps/web/src/components/mode/ModeScreen.tsx
  apps/web/src/components/photo/PhotoPreview.tsx
  apps/web/src/lib/api.ts
Labels: 🐛 バグ

#64 Feature/56/change catchphrase
  apps/web/src/components/home/HomeScreen.tsx
Labels: 🎨 UI改善, 🖥️ フロントエンド

#66 撮影画面のカウントダウンを実装
  apps/web/src/components/photo/PhotoPreview.tsx
  apps/web/src/components/photo/PhotoScreen.module.css
  apps/web/src/components/photo/PhotoScreen.tsx
Labels: 🎨 UI改善, 🖥️ フロントエンド

#69 ホーム画面のタイトルフォントを変更
  apps/web/src/components/home/HomeScreen.module.css
  apps/web/src/components/home/HomeScreen.tsx
  apps/web/src/components/photo/PhotoPreview.module.css
  apps/web/src/components/photo/PhotoPreview.tsx
  apps/web/src/components/photo/PhotoScreen.module.css
  apps/web/src/index.css
Labels: 🎨 UI改善, 🖥️ フロントエンド

#78 Gemini のモデルを安価なモデルに変更
  apps/api/src/services/google/gemini-api.ts
Labels: ⚙️ バックエンド
